baseurl = "https://traceintime.com"
defaultContentLanguage = "en"
languageCode = "en"
title = "Trace in Time"
theme = "dream"
timeout = "240s"

enableRobotsTXT = true
enableGitInfo = true

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[services]
[services.disqus]
shortname = "trace-in-time"
[services.googleAnalytics]
ID = "G-1YC6XZCNZP"

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "Mohamed Halawa"
# description = ""
avatar = "img/logo.png"
headerTitle = "Trace in Time"
motto = "A moment to reflect"

# footerBottomText = ""

rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "imhalawa@outlook.com"

siteStartYear = 2024

favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = false
reorderNavItems = [
    "about",
    "resume",
    "search",
    "posts",
    "categories",
    "tags",
    "rss",
]
collapseNavItems = ["posts", "categories", "tags", "rss"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = false
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

[params.advanced]
customCSS = []
customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy-MM-dd"
