#-------------------------------
# Site Settings
title: Trace in Time
description: Trace in Time is a super modern and unique Jekyll blog theme
logo: # You can add own logo. For example '/images/logo.png'.
logo_dark:


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: light # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Videos'
      url: '/videos/'
    - title: 'Books'
      url: '/books/'
    - url: '/about/'
      title: 'About'
    - title: 'Pages'
      submenu:
      - url: '/contact/'
        title: 'Contact'
      - title: 'Archive'
        url: '/archive/'


#-------------------------------
# Author Settings
author:
  author_name: Mohamed Halawa
  author_avatar: /images/author/profile.png


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: /images/author/profile.png
  hero_title: Hi! I’m Mohamed
  hero_subtitle: Software engineer, hobbyist photographer, and explorer of meaning and systems
  hero_description: |
    I build systems that make sense — turning ideas into structure, and structure into results.

    Here, I share what I build, photograph, and learn — notes on finding clarity, staying creative, and making progress one step at a time.
  hero_image: /images/site_identity/hero.png # TODO: change image to my own desktop setup
  hero_image_caption: This space is a trace in time — fragments of systems and reflections
  hero_button_text: Let’s Connect!
  hero_button_link: '/contact/'


# Logos
# logos:
#   enable: true
#   logos_title: Nerd Stuff
#   logo_image:
#     - alt: "Game Boy"
#       image: "/images/1000.jpg"
#     - alt: "Super Nintendo"
#       image: "/images/1001.jpg"
#     - alt: "Keyboard"
#       image: "/images/1002.jpg"
#     - alt: "Headphones"
#       image: "/images/1003.jpg"
#     - alt: "Mouse"
#       image: "/images/1004.jpg"


#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: Traces


#-------------------------------
# Tags Section Settings
tags_section: # TODO: enable tags section later when we launch the first series of posts
  enable: false
  tags_section_title: Threads
  tags:
    - tag: "Structures"
      image: "/images/20.jpg"


#-------------------------------
# Videos Section Settings
videos_section:
  enable: false
  videos_section_title: Latest Videos


#-------------------------------
# Gallery Section Settings
gallery_section:
  enable: false # TODO: enable gallery section later when we have more footages
  gallery_section_title: Footages
  gallery:
    gallery_images:
      - alt: 'Rest'
        url: '/images/100.jpg'
        caption: 'Small steps lead to big results.'
      - alt: 'Lifestyle'
        url: '/images/101.jpg'
        caption: 'A peaceful moment captured during a serene evening.'
      - alt: 'Hobby'
        url: '/images/102.jpg'
        caption: 'True friends are like stars — they shine brightest when the world feels dark.'
      - alt: 'Computers'
        url: '/images/103.jpg'
        caption: 'Every click opens a new chapter in an endless story.'
      - alt: 'Games'
        url: '/images/104.jpg'
        caption: 'Every level is a new opportunity to test your limits.'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Stay inspired weekly ✌️
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Now


#-------------------------------
# Footer Settings
footer_description: Here, I share what I build, photograph, and learn along the way — thoughts on keeping creativity alive inside a structured life. You’ll find reflections, tools, and methods that help me stay focused without losing curiosity. Dive in, and maybe you’ll find something that resonates.


#-------------------------------
# Social Settings
social:
# - {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
# - {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://facebook.com"}
# - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# - {icon: "fa-brands fa-reddit-alien", name: "Reddit", link: "https://reddit.com"}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://linkedin.com/in/imhalawa"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/imhalawa"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com/im.halawa"}
- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: xeopjzgw # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id